### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/batchlib#29]
The logging can still be improved.

- [x] currently only one of the messages goes to the log file, the rest is printed to the command line
- [ ] a lot of important things are not logged yet, e.g. input output checks

**Comment by constantinpape** [comment]
@wolny 

When I run the pixel-level analysis, I get this in the log file:
```
2020-04-16 13:05:18,124 [MainThread] INFO Workflow - Running workflow: 'PixelAnalysisWorkflow1'. Job spec: {<bound method Preprocess.from_folder of <class 'batchlib.preprocessing.preprocess.Preprocess'>>: {'build': {'input_folder': '../data/test_inputs', 'barrel_corrector_path': '../misc/barrel_corrector.h5', 'scale_factors': None}, 'run': {'n_jobs': 4}}, <class 'batchlib.segmentation.ilastik_prediction.IlastikPrediction'>: {'build': {'ilastik_bin': '../../antibodies-nuclei/ilastik/run_ilastik.sh', 'ilastik_project': '../../antibodies-nuclei/ilastik/local_infection.ilp', 'input_key': ['nuclei_corrected',
'marker_corrected', 'serum_corrected'], 'output_key': ['local_infected', 'local_not_infected'], 'keep_channels': [0, 1], 'scale_factors': None}, 'run': {'n_jobs': 4, 'n_threads': 4}}, <class 'batchlib.analysis.pixel_level_analysis.PixellevelAnalysis'>: {'build': {'serum_key': 'serum_corrected', 'infected_key': 'local_infected', 'not_infected_key': 'local_not_infected', 'output_folder': 'pixelwise_analysis_corrected'}, 'run': {'n_jobs': 4}}}
```
the rest is printed on the command line.
I think ideally, we should see the log messages both on the command line and i the log file.

I will take care of more logging at some point.

**Comment by wolny** [comment]
@constantinpape that should only be the case if the logger you're using is not a child of the `Workflow` logger.

Basically I threat the `Workflow` logger as the main logger and register all the file/console handlers there if necessary. If we want another logger to be able to log to the same destination (handlers) it must be named accordingly (i.e. be the child of the parent logger).

As an example:
```
l1 = get_logger('Workflow')
add_file_handler(l1, 'work_dir', 'workflow_name')

# in the job class or somewhere else
l2 = get_logger('Workflow.Job1') # this is the child logger of the 'Workfow' logger
l2.info('some message') # the message will be propagated to all the handlers in the parent logger
```
I wrote a couple of tests to see if everything is working correctly: https://github.com/hci-unihd/batchlib/blob/master/test/util/test_logging.py but I'll double-check it...

**Comment by constantinpape** [comment]
> @constantinpape that should only be the case if the logger you're using is not a child of the `Workflow` logger.

I haven't really changed anything with the loggers after I merged your PR.

> I wrote a couple of tests to see if everything is working correctly: https://github.com/hci-unihd/batchlib/blob/master/test/util/test_logging.py but I'll double-check it...

Yes, would be great if you can double check. In addition to the tests, try running one of the workflows, I think this should show that it doesn't quite work right now.

> Maybe also I should document that briefly in the README.

Yes, that would be great.

**Comment by wolny** [comment]
JTLYK: @constantinpape it was indeed a bug: file handler was being removed from the workflow logger inside the job loop, preventing any subsequent logging to be directed to the file. I fixed that in https://github.com/hci-unihd/batchlib/commit/22e859f1df854ed0f7dae51233ada7291643cea5. Additionally I've redirected the tensorflow logs into the file as well (only WARN level and above are directed to the file, which is good IMO, cause TF spits out quite a bit).
I've skipped the logging of `tqdm` progress bar, cause it's a lot of additional boiler plate (https://github.com/tqdm/tqdm/issues/313) and I'd rather log the files being processed manually.

**Comment by constantinpape** [comment]
> file handler was being removed from the workflow logger inside the job loop, preventing any subsequent logging to be directed to the file. I fixed that in [22e859f](https://github.com/hci-unihd/batchlib/commit/22e859f1df854ed0f7dae51233ada7291643cea5).

Hmm, I checked again and I am still not quite sure if it works properly.
But I will implement a bit more logging now and then check again and let you know.

> Additionally I've redirected the tensorflow logs into the file as well (only WARN level and above are directed to the file, which is good IMO, cause TF spits out quite a bit).

Yes, I agree that's good.

> I've skipped the logging of `tqdm` progress bar, cause it's a lot of additional boiler plate ([tqdm/tqdm#313](https://github.com/tqdm/tqdm/issues/313)) and I'd rather log the files being processed manually.

Yes, I wouldn't log tqdm either; it's very helpful to see this while running the job directly and I don't see many benefits of having this in the log.

**Comment by constantinpape** [comment]
Ok, I checked again and it works as expected now :).
Thanks @wolny.

I also added some more logging, gonna add some more tomorrow and then close this.

**Comment by wolny** [comment]
awesome, cheers!

**Comment by constantinpape** [comment]
We are logging the most important things now.
